language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install

script:
  - find src -type f -name "*.php" | xargs -n 1 php -l
  - composer run test
  - composer run phpcs
